In [1]:
# Imports.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Load data.
sellData = pd.read_csv('Properati-Data.csv')

In [3]:
# Take a quick look.
sellData.head()

,id,created_on,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,...,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url,description,title,image_thumbnail
0,c8a66ee9e3da083ab66dacd165e8a5cc718b1cf2,2012-09-19,sell,house,San Antonio De Padua,|Argentina|Bs.As. G.B.A. Zona Oeste|Merlo|San ...,Argentina,Bs.As. G.B.A. Zona Oeste,3429244.0,NaN,...,93.0,360.360360,1290.322581,NaN,NaN,NaN,http://www.properati.com.ar/udh_venta_casa_mer...,CASA CON LOCAL EN VENTA EN PADUA.2 DORMITORIOS...,CASA EN VENTA,https://thumbs4.properati.com/1/ufoyqwscVk8n3e...
1,a205c53378e7879cf7519659317fb410c060d20e,2012-10-22,sell,house,San Antonio De Padua,|Argentina|Bs.As. G.B.A. Zona Oeste|Merlo|San ...,Argentina,Bs.As. G.B.A. Zona Oeste,3429244.0,NaN,...,220.0,1000.000000,1000.000000,NaN,NaN,NaN,http://www.properati.com.ar/20hi_venta_casa_me...,CHALET VENTA 4 AMBIENTES PADUA.EXCELENTE CHALE...,CASA EN VENTA,https://thumbs4.properati.com/5/I5RS_jAIUseo9H...
2,e06d6f864a0b91346594da4d27ceddcef0947ea6,2012-11-01,sell,apartment,Mar del Plata,|Argentina|Buenos Aires Costa Atlántica|Mar de...,Argentina,Buenos Aires Costa Atlántica,3430863.0,"-38.0199509,-57.5265733",...,42.0,NaN,NaN,NaN,2.0,NaN,http://www.properati.com.ar/336o_venta_departa...,DTO. 2 AMB. C/ VISTA PLENA AL 6 X 3DOMITORIO ...,DTO. 2 AMB. C/ VISTA PLENA AL MAR,https://thumbs4.properati.com/5/VjDOdzm9n8uqZu...
3,a07927207d2a03de5f4ba7fd76f670d6285a3315,2012-11-26,sell,house,Sierra de los Padres,|Argentina|Buenos Aires Interior|General Pueyr...,Argentina,Buenos Aires Interior,3427958.0,"-37.9511934894,-57.7752885836",...,265.0,NaN,NaN,NaN,6.0,NaN,http://www.properati.com.ar/47hc_venta_terreno...,PROPIEDAD DE CATEGORIA CUENTA CON: 4 DORMITOR...,CHALET EN VENTA,https://thumbs4.properati.com/9/DA4GMdxXrthh5z...
4,9446052c949050359fb08b9f1ba83ba2eaa20c99,2012-12-08,sell,house,Mataderos,|Argentina|Capital Federal|Mataderos|,Argentina,Capital Federal,3430787.0,"-34.6544492346,-58.4895603251",...,103.0,616.666667,1796.116505,NaN,5.0,NaN,http://www.properati.com.ar/4m4m_venta_casa_ma...,Casa Multifamiliar en Mataderos!!! Sobre lote ...,CASA EN VENTA,https://thumbs4.properati.com/6/DsNJjCb5_zIPV0...

In [4]:
sellData.tail()

,id,created_on,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,...,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url,description,title,image_thumbnail
187477,91b7a3a73c3d869babaf11a446fad1fd967bc35d,2017-08-01,sell,house,Rosario,|Argentina|Santa Fe|Rosario|,Argentina,Santa Fe,3838574.0,NaN,...,400.0,NaN,NaN,NaN,NaN,NaN,http://www.properati.com.ar/1cjgd_venta_casa_r...,"Excelente casa en venta, ubicada sobre calle S...",Hermosa casa en tres niveles oficina indepen...,https://thumbs4.properati.com/6/TToA8_HfWhSP-a...
187478,aba0d7d6f6f87365d97a4f7bc133f3ef59a70a20,2017-08-01,sell,house,Belgrano,|Argentina|Capital Federal|Belgrano|,Argentina,Capital Federal,3436077.0,"-34.5744697838,-58.4394831816",...,40.0,2700.0,2700.000000,NaN,NaN,1600.0,http://www.properati.com.ar/1cjge_venta_casa_b...,VENTA DEPARTAMENTO 2 AMBIENTES EN BELGRANODepa...,VENTA DEPARTAMENTO 2 AMBIENTES EN BELGRANO,https://thumbs4.properati.com/7/0v8-eKRb7rn0VR...
187479,e935e6dca58a5b2fec2101f8c7ac1494722119a6,2017-08-01,sell,house,Martínez,|Argentina|Bs.As. G.B.A. Zona Norte|San Isidro...,Argentina,Bs.As. G.B.A. Zona Norte,3430813.0,"-34.4961348,-58.5008748",...,95.0,NaN,2610.526316,NaN,NaN,NaN,http://www.properati.com.ar/1cjgi_venta_casa_m...,Excelente duplex 4 ambientes de 5m de frente x...,Casa - San Isidro,https://thumbs4.properati.com/1/XKU2XF2BDkOtcg...
187480,d236e3424ac94ab9fcd5d2c22aed59eeed695adc,2017-08-01,sell,apartment,Villa Luro,|Argentina|Capital Federal|Villa Luro|,Argentina,Capital Federal,3427407.0,"-34.6419903279,-58.4954814907",...,50.0,NaN,2200.000000,NaN,NaN,NaN,http://www.properati.com.ar/1cjgl_venta_depart...,Departameno 1º piso con balcon y terraza a est...,Departamento - Villa Luro,https://thumbs4.properati.com/3/oj0WFPDQeGmrb0...
187481,9439664d30d10181efbae84ed01e6d991087deed,2017-08-01,sell,house,San Carlos de Bariloche,|Argentina|Río Negro|San Carlos de Bariloche|S...,Argentina,Río Negro,3837856.0,NaN,...,161.0,NaN,NaN,NaN,NaN,NaN,http://www.properati.com.ar/1cjgm_venta_casa_s...,Casa ubicada en una de las mejores zonas del B...,Casa - Villa Los Coihues,https://thumbs4.properati.com/1/m_x_wcwgC9IWP0...

In [8]:
# Information about the dataset
sellData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187482 entries, 0 to 187481
Data columns (total 27 columns):
id                            187482 non-null object
created_on                    187482 non-null object
operation                     187482 non-null object
property_type                 187482 non-null object
place_name                    187447 non-null object
place_with_parent_names       187482 non-null object
country_name                  187482 non-null object
state_name                    187482 non-null object
geonames_id                   158318 non-null float64
lat-lon                       118761 non-null object
lat                           118761 non-null float64
lon                           118761 non-null float64
price                         154443 non-null float64
currency                      154441 non-null object
price_aprox_local_currency    154443 non-null float64
price_aprox_usd               154443 non-null float64
surface_total_in_m2           125027 non-null float64
surface_covered_in_m2         152420 non-null float64
price_usd_per_m2              105024 non-null float64
price_per_m2                  131665 non-null float64
floor                         14294 non-null float64
rooms                         80320 non-null float64
expenses                      17520 non-null float64
properati_url                 187482 non-null object
description                   187473 non-null object
title                         187482 non-null object
image_thumbnail               182814 non-null object
dtypes: float64(13), object(14)
memory usage: 38.6+ MB

In [9]:
# Info about the columns of the dataset.
sellData.columns

Index([u'id', u'created_on', u'operation', u'property_type', u'place_name',
       u'place_with_parent_names', u'country_name', u'state_name',
       u'geonames_id', u'lat-lon', u'lat', u'lon', u'price', u'currency',
       u'price_aprox_local_currency', u'price_aprox_usd',
       u'surface_total_in_m2', u'surface_covered_in_m2', u'price_usd_per_m2',
       u'price_per_m2', u'floor', u'rooms', u'expenses', u'properati_url',
       u'description', u'title', u'image_thumbnail'],
      dtype='object')

In [11]:
# Info about numerics attributes of the dataset.
sellData.describe()

,geonames_id,lat,lon,price,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses
count,1.583180e+05,118761.000000,118761.000000,1.544430e+05,1.544430e+05,1.544430e+05,125027.000000,152420.000000,1.050240e+05,1.316650e+05,14294.000000,80320.000000,1.752000e+04
mean,3.560821e+06,-34.775631,-59.207578,4.402848e+05,4.298946e+06,2.436423e+05,297.023707,146.026630,1.980865e+03,6.125528e+03,14.584301,3.087276,4.872184e+03
std,3.442029e+05,2.071562,2.293300,1.915257e+06,6.870371e+06,3.893775e+05,2072.795972,2617.149603,4.624897e+03,2.567322e+04,103.573137,1.754502,1.105076e+05
min,3.427208e+06,-54.833014,-75.678931,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,6.275958e-02,1.000000,1.000000,1.000000e+00
25%,3.430116e+06,-34.729040,-58.718531,1.050000e+05,1.552716e+06,8.800000e+04,52.000000,47.000000,1.024065e+03,1.475000e+03,1.000000,2.000000,8.900000e+02
50%,3.433359e+06,-34.604154,-58.483665,1.800000e+05,2.558452e+06,1.450000e+05,95.000000,80.000000,1.675000e+03,2.096774e+03,3.000000,3.000000,1.800000e+03
75%,3.832260e+06,-34.457223,-58.383317,3.950000e+05,4.728726e+06,2.680000e+05,246.000000,160.000000,2.356604e+03,3.164667e+03,6.000000,4.000000,3.800000e+03
max,6.948895e+06,4.545843,-40.149218,6.500000e+08,8.212711e+08,4.654544e+07,200000.000000,987897.000000,1.271027e+06,4.000000e+06,3150.000000,40.000000,1.000150e+07